# Generated by Django 3.1.3 on 2020-12-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
    ]
