# Generated by Django 3.1.3 on 2020-12-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abk', '0002_auto_20201211_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
    ]
